# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-22 18:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='lab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='lab.Lab'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='userProfile.UserProfile'),
        ),
        migrations.AlterField(
            model_name='appointmenttestmapping',
            name='appointment_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='appointment.Appointment'),
        ),
        migrations.AlterField(
            model_name='appointmenttestmapping',
            name='clinical_test_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='lab.ClinicalTest'),
        ),
    ]
