# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-22 18:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0002_auto_20181021_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicaltest',
            name='lab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='lab.Lab'),
        ),
        migrations.AlterField(
            model_name='labschedule',
            name='lab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='lab.Lab'),
        ),
    ]
